# Generated by Django 2.2.11 on 2020-03-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date_start',
        ),
    ]
