# Generated by Django 2.2.11 on 2020-03-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200330_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_doc',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_prav',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='date_doc',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='date_prav',
        ),
        migrations.RemoveField(
            model_name='genericexpense',
            name='date_reg',
        ),
    ]
