# Generated by Django 2.2.11 on 2020-03-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200330_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='date_doc',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date_prav',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='date_reg',
        ),
    ]
